### ISSUE TITLE
Ignition not realistic when throttle not engaged

### ISSUE THREAD

**Issue by Sultavespa** [ange-yaghi/engine-sim#293]
Hey, so I found that when the engine is in gear and running (For example in 3rd gear at 40 mph) when you let go on the throttle you can see that the engine is still firing (On the top right corner) and in a real car when you lift your foot off the throttle the engine just moves because of the inertia and the movement that the wheels give to the driveshaft, so to make this sim a bit more realistic you could make it so that it just fires when in this cases; Neutral, when clutch is engaged and when in gear whilst using throttle.

**Comment by DDev247** [comment]
This simulator simulates a carburetor and a magneto-styled "coil" so it doesn't work like an EFI system in terms of fuel injection and ignition. Since an EFI system knows everything, it can stop firing/stop fuel delivery when needed.
I hope that explains the confusion.
Links for carburetor and magneto ignition: [Carburetor on Wikipedia](https://en.wikipedia.org/wiki/Carburetor) and [Magneto Ignition on Wikipedia](https://en.wikipedia.org/wiki/Ignition_magneto)

PS: You can see the carburetor simulation when you try to decelerate with ignition off. You will see the fuel consumption increase even though technically it wouldn't happen on an EFI system.

**Comment by ange-yaghi** [comment]
This is intentional behavior and correct for the older engines I designed the simulation for.
