### ISSUE TITLE
Fuel consumption is senselessly capped

### ISSUE THREAD

**Issue by torokati44** [ange-yaghi/engine-sim#326]
So, I was just watching a couple videos about silly engine designs simulated in this software, and I noticed that even with ridiculously low fuel efficiencies (say, 0.2 MPG), the consumption in _proper_ units is never above 100 l / 100 km.
Which simply does not make sense, it's not that the number can't be larger than 100 because that would be more than 1 or something.
An engine should be perfectly capable of consuming way more than 100 liters of fuel over a stretch of 100 km. The 100 km is just a usual and convenient range over which the measurement is done, but the 100 there is by no means a limit for the consumption.

So, this capping here should be removed:
https://github.com/ange-yaghi/engine-sim/blob/7b71a2dc630e843cfe01cda260373dd89f72582f/src/fuel_cluster.cpp#L85

**Comment by torokati44** [comment]
And yes, it should `l/100km`. Capitalization matters AFAIK.

**Comment by ange-yaghi** [comment]
Closing this due to metric superiority complex and annoying wording. Please try again. Also, I don't intend to fix this, it's for cosmetic purposes only.

**Comment by torokati44** [comment]
Ooof, okay, I deserved that. But aside from that, you realize that the code is _objectively incorrect_, right?
I don't care much whether or not you fix it, but I essentially provided the fix already, so up to you if you include it or not.

**Comment by ange-yaghi** [comment]
The code is not "objectively incorrect." It was a deliberate decision to limit it to 100 for display purposes since the supposedly "proper" unit for fuel efficiency blows up to huge numbers when engines first start and idle without moving the vehicle while MPG does not. 100 was a reasonable value for my purposes because I was not planning to make any engines that operate outside that range. Some people have now started making meme engines with unrealistic inputs which exceed this limit.

If you actually want to get this fixed, I suggest opening a new ticket and asking politely. If you had opened a ticket that just said "raise the limit for l/100km for extremely inefficient engines" I would have finished this already.

Also the capitalization is that way because the font that is used by the simulator is capital letters only. The code is a bit inconsistent because I sometimes use all-caps and sometimes not, but for new code I try to stay with the all-caps convention to match how it's displayed.
