### ISSUE TITLE
cant open on macbook

### ISSUE THREAD

**Issue by failed101** [ange-yaghi/engine-sim#402]

**Comment by BoogieHasFun** [comment]
its not meant for macbooks

**Comment by Noah-Barlett** [comment]
This is because MacBooks don't support .exe files

**Comment by failed101** [comment]
well, he should have a mac version, all he needs is to make it a .dmg file

**Comment by MilkMan1093** [comment]
> well, he should have a mac version, all he needs is to make it a .dmg file

There already _is_ a Mac version, you just have to build it yourself.

**Comment by failed101** [comment]
> 

well, can you help me?

**Comment by DDev247** [comment]
> well, he should have a mac version, all he needs is to make it a .dmg file

No. This is not how computers work.
The `.exe` file is intended to be run on Windows machines. It can be run on Linux or macOS using [Wine](https://www.winehq.org/), but the performance can be worse. With that said, you can try running it with Wine (if you are not using an M1/M2 laptop). Install Wine with the official guide at [WineHQ](https://wiki.winehq.org/MacOS), and then double-click on the `.exe` file in the `bin` folder.


> > well, he should have a mac version, all he needs is to make it a .dmg file
> 
> There already _is_ a Mac version, you just have to build it yourself.

And no, this will not work as well. The source code is intended to be compiled using MSVC on Windows. It works with G++ or Clang, but you must clone a [PR](https://github.com/ange-yaghi/engine-sim/pull/346). I'll not provide instructions because I have no experience building it on Linux or macOS. Building it on macOS might actually be impossible, but I'm not sure.

Hope this helps.

**Comment by MilkMan1093** [comment]
> > 
> 
> well, can you help me?

Oh jeez, I'm so sorry, I was so stupid when I said that. Please check the above reply. 😓
