### ISSUE TITLE
May be a bug

### ISSUE THREAD

**Issue by Githubtaxi** [ange-yaghi/engine-sim#406]
Look at this picture
![image](https://user-images.githubusercontent.com/97097706/209492939-36ac0a52-fe14-42d0-8997-1237899a0abb.png)

**Comment by Githubtaxi** [comment]
What's "INF RPM" meaning?

**Comment by ange-yaghi** [comment]
It basically means that the frequency was set too low (which judging by your screenshot appears to be the case) and the physics engine was not able to solve the system resulting in numerical instability and ultimately, complete corruption of the system. At this point it's expected behavior and not a bug.
