### ISSUE TITLE
Enhancement: make each engine bank run on a separate thread

### ISSUE THREAD

**Issue by hurdofdaniel** [ange-yaghi/engine-sim#77]
When running the Chev 454 V8 I get a lot of latency. I was thinking about what could be done to improve performance and if I remember correctly the engine is ran on 1 thread

My idea was to make each bank of cylinders have a separate thread

**Comment by ange-yaghi** [comment]
This is unfortunately not possible. The physics simulation is a linear equation solver and separating that problem into parts is not trivial since the components are all connected to each other. I will be adding a feature to multithread the audio rendering though which should help with this problem.
