### ISSUE TITLE
Idea: Multithreading

### ISSUE THREAD

**Issue by StanTheAwesomeMan** [ange-yaghi/engine-sim#87]
You could split the pistons into individual threads, run the calculation for that frame and wait for all of them to finish, then exchange data and continue with the next frame. That could improve stability, as windows will manage thread balancing and performance, because more threads=more power.

**Comment by cmdrscotty** [comment]
> More threads != necessarily more power. You always have some overhead when switching between threads, synchronization, data transfer... If that overhead is too much, you gain nothing by using threads. 

Likely continued optimization of the current code will offer more improvement over switching to multithreading.

I initially tried the 0.1.5 release and it was chugging hard on a 4 cylinder model on my FX-9590

Downloaded 0.1.7a and tried the same engine, runs very well now.

I could see some edge cases where running a monstrous amount of cylinders (32 or more?) May get into the realm where multithreading would offer benefits

**Comment by raspitakesovertheworld** [comment]
> More threads != necessarily more power. You always have some overhead when switching between threads, synchronization, data transfer... If that overhead is too much, you gain nothing by using threads.

That is not reasonable: We now live in a multi core CPU world, pretty much all power that we get from the CPU is now multithreaded only, as CPU clocks have not increased that much in the last 20 years since we went away from single cores. The overhead is never so large that it eats up all power, even if overhead would be 20%, you still get a lot extra power, as any CPU today has at least 4 cores, high performance CPUs have 8 or even 16 cores. Each core can usually take two threads to fully saturate it, that is why hyperthreading exists.

So your claim that more threads does not automatically mean more power is clearly false. There are some physics simulations that cannot be parallelized, I'm not sure if this is one, but many things can be.

**Comment by Jckf** [comment]
> That is not reasonable: We now live in a multi core CPU world, pretty much all power that we get from the CPU is now multithreaded only, as CPU clocks have not increased that much in the last 20 years since we went away from single cores. The overhead is never so large that it eats up all power, even if overhead would be 20%, you still get a lot extra power, as any CPU today has at least 4 cores, high performance CPUs have 8 or even 16 cores. Each core can usually take two threads to fully saturate it, that is why hyperthreading exists.

Clock speed and performance cannot be compared. You have to look at IPC count to get some idea of how the frequency relates to performance, but even that doesn't tell the whole story. Your comment makes it seem like we haven't had any advancement in CPU performance since the early 2000s when a P4 could easily be ran at 4 GHz plus.

> So your claim that more threads does not automatically mean more power is clearly false. There are some physics simulations that cannot be parallelized, I'm not sure if this is one, but many things can be.

Not all workloads are easily multithreaded, or can be multithreaded at all. @HWiese1980 is correct in saying that splitting the work into more threads is not a guarantied win for all scenarios.

Discussion closed.
