### ISSUE TITLE
Vukan-1.dll not found

### ISSUE THREAD

**Issue by fvkelley** [ange-yaghi/engine-sim#91]
When trying to run the simulator under 1.5.a it cannot run because it says:
"The code execution cannot proceed because vukan-1.dll was not found. Reinstalling the program may fix this problem."

**Comment by ange-yaghi** [comment]
I'll see about adding this DLL to the build.

**Comment by NotoriusNeo** [comment]
Duplicate of #45 

You need to install this: https://developer.nvidia.com/vulkan-driver

**Comment by klertimalaj** [comment]
what if you dont have a nvidia gpu? i have intel hd and cant download that, how am i supposed to run the engine sim?

**Comment by fvkelley** [comment]
@NotoriusNeo 
Ahhh, thanks. However, i am running this on a laptop, an old latitude, and @klertimalaj is right, can I run a nvidia file on my laptop?
P.S.: I am sorry about the duplicate; I did not see it.

**Comment by klertimalaj** [comment]
I found it! You can just download a dll vulkan file from chrome and you're good to go!

**Comment by Krenodeno** [comment]
Vulkan DLL should be bundled with your graphic card drivers. First check that your GPU does have support for Vulkan Graphic API, and then check your drivers are up to date.

@ange-yaghi You could ship the dll with the app, but I'm not sure it is recommended.
There is this SO thread where the different approaches are discussed : https://stackoverflow.com/questions/38334158/vulkan-sdk-redistributables
It is said that for the majority, it should go with the installed drivers of the users' graphic card. But you can also use their "Vulkan RunTime Installer" in order to install the needed dependencies for Vulkan.
